name: Action Commands

on: [push]

jobs:
  my-job:
    name: My Job3
    runs-on: ubuntu-latest
    steps:
      - name: List File
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: action/checkout@main
      - name: List File despues checkout
        run: |
          pwd
          ls -a
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rafa
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"