name: Shell Commands

on: [push]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
    - name: multiline script
      run: |
        node -v
        npm  -v