name: shell Commands

on: [push]

jobs:
    run-shell-Commands:
      run-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Hello World"
        - name:  multiline script
          run: |  
              node -v
              npm -v
